# Generated by Django 6.0 on 2026-02-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usernotify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotify',
            name='type',
            field=models.CharField(blank=True, choices=[('USERNOTIFY', 'UserNotify'), ('INCHROOMNOTIFY', 'InChatroomNotify')], default='USERNOTIFY', null=True),
        ),
    ]
