# Generated by Django 6.0 on 2026-02-22 22:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_customuser_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connect',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('url', models.URLField(verbose_name='URL')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='connect',
            field=models.ManyToManyField(blank=True, to='users.connect'),
        ),
    ]
