# Generated by Django 6.0 on 2026-02-26 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_connect_profile_connect'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total_views',
            field=models.IntegerField(default=0),
        ),
    ]
