# Generated by Django 6.0 on 2026-02-26 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_total_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='connect',
        ),
        migrations.AddField(
            model_name='connect',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
