# Generated by Django 6.0 on 2026-02-26 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_profile_connect_connect_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connect',
            name='user',
        ),
        migrations.AddField(
            model_name='connect',
            name='profile',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='connect', to='users.profile'),
        ),
    ]
