# Generated by Django 6.0 on 2026-02-26 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_connect_user_connect_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connect',
            name='profile',
        ),
        migrations.AddField(
            model_name='connect',
            name='profile',
            field=models.ManyToManyField(default='', related_name='connect', to='users.profile'),
        ),
    ]
