# Generated by Django 6.0 on 2026-02-26 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_connect_profile_connect_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connect',
            name='profile',
        ),
        migrations.AddField(
            model_name='profile',
            name='connects',
            field=models.ManyToManyField(blank=True, to='users.connect'),
        ),
    ]
