# Generated by Django 6.0 on 2026-03-01 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_verificationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationrequest',
            name='birth_date',
            field=models.DateField(null=True, verbose_name='Birth Date'),
        ),
    ]
