# Generated by Django 6.0 on 2026-03-01 17:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_verificationrequest_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationrequest',
            name='content',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='verificationrequest',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
