# Generated by Django 6.0 on 2026-03-01 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_verificationrequest_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationrequest',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Is Approved'),
        ),
    ]
