# Generated by Django 6.0 on 2026-03-02 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_verificationrequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationrequest',
            name='note_admin',
            field=models.TextField(blank=True, max_length=5000),
        ),
        migrations.AlterField(
            model_name='verificationrequest',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
