# Generated by Django 6.0 on 2026-03-04 06:51

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_remove_verificationrequest_is_approved_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Message', 'Chat Message Notification'), ('Warning', 'Warning Notification'), ('System', 'System Notification')], max_length=50, verbose_name='Type')),
                ('content', models.TextField(blank=True, max_length=5000)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='notifications',
            field=models.ManyToManyField(blank=True, to='users.notification'),
        ),
    ]
