# Generated by Django 6.0 on 2026-03-04 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_notification_profile_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
