# Generated by Django 6.0 on 2026-03-08 00:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_notification_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPunishment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('BAN', 'BAN'), ('MUTE', 'MUTE')], default='', max_length=50, verbose_name='Type')),
                ('reason', models.TextField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('staff', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='staff', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
