# Generated by Django 6.0 on 2026-03-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_userpunishment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpunishment',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
