# Generated by Django 6.0 on 2026-03-08 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_customuser_email_verification_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='username'),
        ),
    ]
