# Generated by Django 6.0 on 2026-03-08 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email_verification_code',
            field=models.CharField(default='', max_length=6, null=True, verbose_name='Email Verification Code'),
        ),
    ]
